try another deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,19 +21,22 @@ jobs:
       - name: SSH and deploy
         run: |
           ssh ${{secrets.SSH_USERNAME}}@${{secrets.SSH_PUBLIC_IP}} "
-            echo "Changing directory..."
-            cd aws-practice || { echo "Directory 'aws-practice' not found"; exit 1; }
-            echo "Pulling latest code..."
-            git config pull.rebase false  # Choose merge strategy (or use true for rebase, or 'ff only') || exit 1
+            echo 'Changing directory...'
+            cd aws-practice || { echo 'Directory aws-practice not found'; exit 1; }
+            echo 'Pulling latest code...'
+            git config pull.rebase false || exit 1
             git pull || exit 1
-            echo "Installing npm dependencies..."
+            echo 'Installing npm dependencies...'
             npm install || exit 1
-            echo "Building project..."
+            echo 'Building project...'
             npm run build || exit 1
-            echo "Stopping existing node processes..."
+            echo 'Stopping existing node processes...'
             sudo pkill node
-            echo "Starting the application..."
-            nohup sudo npm run start & 
-            echo "Exiting..."
+            echo 'Starting the application...'
+            sudo npm run start > server.log 2>&1 &  # Run server in background but keep session open
+            echo 'Waiting for the server to start...'
+            npx wait-on http://localhost || { echo 'Server did not start'; exit 1; }
+            echo 'Server is up and running!'
+            echo 'Exiting...'
             exit
           "
